In [1]:
from adbench import datasets, classifiers
from sklearn.metrics import precision_score, recall_score, f1_score

# Define the anomaly detection algorithms (unsupervised and semi-supervised)
unsupervised_algorithms = {
    "LOF": classifiers.LOF(),
    "ABOD": classifiers.ABOD(),
    "Isolation Forest": classifiers.IsolationForest(),
}
semi_supervised_algorithms = {
    "Autoencoder": classifiers.Autoencoder(),
    "LUNAR": classifiers.LUNAR(),
}

# Load a dataset (replace 'your_dataset_name' with an appropriate dataset from adbench)
dataset = datasets.load(name="your_dataset_name")

# Perform anomaly detection for unsupervised algorithms
for name, algorithm in unsupervised_algorithms.items():
    print(f"Running {name} on {dataset.name}")
    predictions = algorithm.fit_predict(dataset.data)
    ground_truth = dataset.target  # Assuming ground truth labels are available

    # Evaluate the results using precision, recall, F1-score
    precision = precision_score(ground_truth, predictions)
    recall = recall_score(ground_truth, predictions)
    f1 = f1_score(ground_truth, predictions)

    print(f"Evaluation Results ({name}):")
    print(f"\tPrecision: {precision:.4f}")
    print(f"\tRecall: {recall:.4f}")
    print(f"\tF1-score: {f1:.4f}")
    print("-" * 30)  # Separator

# Perform anomaly detection for semi-supervised algorithms (assuming labeled data is available)
labeled_data = # Prepare your labeled data with normal and anomaly points
for name, algorithm in semi_supervised_algorithms.items():
    print(f"Running {name} on {dataset.name}")
    predictions = algorithm.fit_predict(dataset.data, labeled_data)
    ground_truth = dataset.target  # Assuming ground truth labels are available

    # Evaluate the results using precision, recall, F1-score
    precision = precision_score(ground_truth, predictions)
    recall = recall_score(ground_truth, predictions)
    f1 = f1_score(ground_truth, predictions)

    print(f"Evaluation Results ({name}):")
    print(f"\tPrecision: {precision:.4f}")
    print(f"\tRecall: {recall:.4f}")
    print(f"\tF1-score: {f1:.4f}")
    print("-" * 30)  # Separator


SyntaxError: invalid syntax (1898754215.py, line 36)

In [7]:
import numpy as np

dataset = np.load('10_cover.npz')
dataset_keys = dataset.keys()
for key in dataset_keys:
    print(f"Contents of {key}:")
    print(dataset[key])

dataset['X'].shape

Contents of X:
[[2804  139    9 ...  238  135 6121]
 [2785  155   18 ...  238  122 6211]
 [2579  132    6 ...  237  140 6031]
 ...
 [2612   17   13 ...  211  138  644]
 [2610   16   14 ...  211  138  671]
 [2608   23   14 ...  209  131  698]]
Contents of y:
[0 0 0 ... 0 0 0]


(286048, 10)